GET http://localhost:3000/todo
Accept: application/json

###

GET http://localhost:3000/todo/64280b6601e6c1438f31d2b0
Accept: application/json


###

POST http://localhost:3000/todo
Content-Type: application/json
Accept: application/json

{
  "title": "My first todo",
  "description": "This is my first todo",
  "completed": false
}

###

DELETE http://localhost:3000/todo/64280b6601e6c1438f31d2b0
Accept: application/json


###

PUT http://localhost:3000/todo/64280b44e95ae56809eac119
Content-Type: application/json
Accept: application/json

{
  "title": "My this 3rd todo",
  "description": "This is my 3rd todo",
  "completed": true
}


###

PUT http://localhost:3000/todo/complete/64280b44e95ae56809eac119
Content-Type: application/json
Accept: application/json



###

