GET http://localhost:3000/todo
Accept: application/json

###

GET http://localhost:3000/todo/1
Accept: application/json


###

POST http://localhost:3000/todo
Content-Type: application/json
Accept: application/json

{
  "title": "My first todo",
  "description": "This is my first todo",
  "completed": false
}

###

DELETE http://localhost:3000/todo/9
Accept: application/json


###

PUT http://localhost:3000/todo/3
Content-Type: application/json
Accept: application/json

{
  "title": "My this 3rd todo",
  "description": "This is my 3rd todo",
  "completed": true
}


###

PUT http://localhost:3000/complete/4
Content-Type: application/json
Accept: application/json


###
